//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.3053
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Data.Types
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItemRow", Namespace="http://schemas.datacontract.org/2004/07/Spinit.Wpc.Synologen.Data.Types")]
    public partial class OrderItemRow : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ArticleDisplayNameField;
        
        private string ArticleDisplayNumberField;
        
        private int ArticleIdField;
        
        private float DisplayTotalPriceField;
        
        private int IdField;
        
        private string NotesField;
        
        private int NumberOfItemsField;
        
        private int OrderIdField;
        
        private float SinglePriceField;
        
        private int TemporaryIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArticleDisplayName
        {
            get
            {
                return this.ArticleDisplayNameField;
            }
            set
            {
                this.ArticleDisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArticleDisplayNumber
        {
            get
            {
                return this.ArticleDisplayNumberField;
            }
            set
            {
                this.ArticleDisplayNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArticleId
        {
            get
            {
                return this.ArticleIdField;
            }
            set
            {
                this.ArticleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DisplayTotalPrice
        {
            get
            {
                return this.DisplayTotalPriceField;
            }
            set
            {
                this.DisplayTotalPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfItems
        {
            get
            {
                return this.NumberOfItemsField;
            }
            set
            {
                this.NumberOfItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float SinglePrice
        {
            get
            {
                return this.SinglePriceField;
            }
            set
            {
                this.SinglePriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemporaryId
        {
            get
            {
                return this.TemporaryIdField;
            }
            set
            {
                this.TemporaryIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderRow", Namespace="http://schemas.datacontract.org/2004/07/Spinit.Wpc.Synologen.Data.Types")]
    public partial class OrderRow : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CompanyIdField;
        
        private string CompanyUnitField;
        
        private System.DateTime CreatedDateField;
        
        private string CustomerFirstNameField;
        
        private string CustomerLastNameField;
        
        private string EmailField;
        
        private int IdField;
        
        private long InvoiceNumberField;
        
        private bool MarkedAsPayedByShopField;
        
        private string PersonalIdNumberField;
        
        private string PhoneField;
        
        private int RSTIdField;
        
        private string RstTextField;
        
        private int SalesPersonMemberIdField;
        
        private int SalesPersonShopIdField;
        
        private int StatusIdField;
        
        private System.DateTime UpdateDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyUnit
        {
            get
            {
                return this.CompanyUnitField;
            }
            set
            {
                this.CompanyUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFirstName
        {
            get
            {
                return this.CustomerFirstNameField;
            }
            set
            {
                this.CustomerFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerLastName
        {
            get
            {
                return this.CustomerLastNameField;
            }
            set
            {
                this.CustomerLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InvoiceNumber
        {
            get
            {
                return this.InvoiceNumberField;
            }
            set
            {
                this.InvoiceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MarkedAsPayedByShop
        {
            get
            {
                return this.MarkedAsPayedByShopField;
            }
            set
            {
                this.MarkedAsPayedByShopField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalIdNumber
        {
            get
            {
                return this.PersonalIdNumberField;
            }
            set
            {
                this.PersonalIdNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RSTId
        {
            get
            {
                return this.RSTIdField;
            }
            set
            {
                this.RSTIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RstText
        {
            get
            {
                return this.RstTextField;
            }
            set
            {
                this.RstTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalesPersonMemberId
        {
            get
            {
                return this.SalesPersonMemberIdField;
            }
            set
            {
                this.SalesPersonMemberIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalesPersonShopId
        {
            get
            {
                return this.SalesPersonShopIdField;
            }
            set
            {
                this.SalesPersonShopIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusId
        {
            get
            {
                return this.StatusIdField;
            }
            set
            {
                this.StatusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateDate
        {
            get
            {
                return this.UpdateDateField;
            }
            set
            {
                this.UpdateDateField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISynologenService")]
public interface ISynologenService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynologenService/GetOrderItemsPerOrder", ReplyAction="http://tempuri.org/ISynologenService/GetOrderItemsPerOrderResponse")]
    Spinit.Wpc.Synologen.Data.Types.OrderItemRow[] GetOrderItemsPerOrder(int orderId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynologenService/GetOrdersForInvoicing", ReplyAction="http://tempuri.org/ISynologenService/GetOrdersForInvoicingResponse")]
    Spinit.Wpc.Synologen.Data.Types.OrderRow[] GetOrdersForInvoicing();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ISynologenServiceChannel : ISynologenService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class SynologenServiceClient : System.ServiceModel.ClientBase<ISynologenService>, ISynologenService
{
    
    public SynologenServiceClient()
    {
    }
    
    public SynologenServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SynologenServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SynologenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SynologenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Spinit.Wpc.Synologen.Data.Types.OrderItemRow[] GetOrderItemsPerOrder(int orderId)
    {
        return base.Channel.GetOrderItemsPerOrder(orderId);
    }
    
    public Spinit.Wpc.Synologen.Data.Types.OrderRow[] GetOrdersForInvoicing()
    {
        return base.Channel.GetOrdersForInvoicing();
    }
}
