
#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Spinit's LINQ to SQL template for T4 C#
//     Generated at 10/22/2009 15:41:29
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

using Spinit.Data.Linq;
using Spinit.Logging;

using Spinit.Wpc.Synologen.Opq.Core;
using Spinit.Wpc.Synologen.Opq.Core.Entities;
using Spinit.Wpc.Synologen.Opq.Data.Entities;

namespace Spinit.Wpc.Synologen.Opq.Data
{
	public partial class WpcSynologenOpqRepository : SpinitRepository
	{
		#region Constructors

		/// <summary>
		/// Constructor whics sets configuration and logging.
		/// </summary>
		/// <param name="configuration">The configuration.</param>
		/// <param name="loggingService">The logging-service.</param>

		public WpcSynologenOpqRepository (
			Configuration configuration,
			ILoggingService loggingService) 
			: base (new WpcSynologenOpqDataContext (configuration.ConnectionString))
		{
			OnCreate ();

			Configuration = configuration;
			
			LoggingService = loggingService;

			TrackingOn = false;
		}

		/// <summary>
		/// Constructor whics sets configuration, logging and tracking.
		/// </summary>
		/// <param name="configuration">The configuration.</param>
		/// <param name="loggingService">The logging-service.</param>
		/// <param name="noTracking">If true=>no tracking.</param>

		public WpcSynologenOpqRepository (
			Configuration configuration,
			ILoggingService loggingService,
			bool noTracking)
			: base (new WpcSynologenOpqDataContext (configuration.ConnectionString).NoTracking ())
		{
			OnCreate ();

			Configuration = configuration;

			LoggingService = loggingService;

			TrackingOn = noTracking;
		}

		/// <summary>
		/// Constructor whics sets configuration, logging and context.
		/// </summary>
		/// <param name="configuration">The configuration.</param>
		/// <param name="loggingService">The logging-service.</param>
		/// <param name="context">The context.</param>

		public WpcSynologenOpqRepository (
			Configuration configuration,
			ILoggingService loggingService,
			SpinitDataContext context)
			: base (context)
		{
			OnCreate ();

			Configuration = configuration;

			LoggingService = loggingService;

			TrackingOn = false;
		}

		#endregion
		
 		
		#region Create Repository

		/// <summary>
		/// Creates the repository with tracking.
		/// </summary>
		/// <param name="configuration">The configuarion.</param>
		/// <param name="loggingService">The logging service.</param>
		/// <returns>A repository</returns>

		public static WpcSynologenOpqRepository GetWpcSynologenOpqRepository (
			Configuration configuration,
			ILoggingService loggingService)
		{
			return new WpcSynologenOpqRepository (
				configuration,
				loggingService);
		}

		/// <summary>
		/// Creates the repository without tracking.
		/// </summary>
		/// <param name="configuration">The configuarion.</param>
		/// <param name="loggingService">The logging service.</param>
		/// <returns>A repository</returns>

		public static WpcSynologenOpqRepository GetWpcSynologenOpqRepositoryNoTracking (
			Configuration configuration,
			ILoggingService loggingService)
		{
			return new WpcSynologenOpqRepository (
				configuration,
				loggingService,
				true);
		}

		#endregion
		
		#region Search

		/// <summary>
		/// Creates a search-table.
		/// </summary>

		protected override void CreateSearchTable ()
		{
			_searchTable = new List<SearchPairs>
			{
				new SearchPairs (typeof (SynologenOpqDocumentHistory), new ESynologenOpqDocumentHistory ()),
				new SearchPairs (typeof (SynologenOpqDocument), new ESynologenOpqDocument ()),
				new SearchPairs (typeof (SynologenOpqDocumentType), new ESynologenOpqDocumentType ()),
				new SearchPairs (typeof (SynologenOpqFileCategory), new ESynologenOpqFileCategory ()),
				new SearchPairs (typeof (SynologenOpqFile), new ESynologenOpqFile ()),
				new SearchPairs (typeof (SynologenOpqNode), new ESynologenOpqNode ()),
				new SearchPairs (typeof (SynologenOpqNodeSupplierConnection), new ESynologenOpqNodeSupplierConnection ()),
			};
		}

		#endregion
		
		#region Global properties

		/// <summary>
		/// Gets or sets the configuration
		/// </summary>

		public Configuration Configuration { get; set; }

		#endregion
	}
		
}
#pragma warning restore 1591
 
