
#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Spinit's LINQ to SQL template for T4 C#
//     Generated at 10/26/2009 13:57:20
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

using Spinit.Data.Linq;
using Spinit.Logging;

using Spinit.Wpc.Synologen.OPQ.Core;
using Spinit.Wpc.Synologen.OPQ.Core.Entities;
using Spinit.Wpc.Synologen.OPQ.Data.Entities;

namespace Spinit.Wpc.Synologen.OPQ.Data
{
	public partial class WpcSynologenRepository : SpinitRepository
	{
		#region Constructors

		/// <summary>
		/// Constructor whics sets configuration and logging.
		/// </summary>
		/// <param name="configuration">The configuration.</param>
		/// <param name="loggingService">The logging-service.</param>

		public WpcSynologenRepository (
			Configuration configuration,
			ILoggingService loggingService) 
			: base (new WpcSynologenDataContext (configuration.ConnectionString))
		{
			OnCreate ();

			Configuration = configuration;
			
			LoggingService = loggingService;

			TrackingOn = false;
		}

		/// <summary>
		/// Constructor whics sets configuration, logging and tracking.
		/// </summary>
		/// <param name="configuration">The configuration.</param>
		/// <param name="loggingService">The logging-service.</param>
		/// <param name="noTracking">If true=>no tracking.</param>

		public WpcSynologenRepository (
			Configuration configuration,
			ILoggingService loggingService,
			bool noTracking)
			: base (new WpcSynologenDataContext (configuration.ConnectionString).NoTracking ())
		{
			OnCreate ();

			Configuration = configuration;

			LoggingService = loggingService;

			TrackingOn = noTracking;
		}

		/// <summary>
		/// Constructor whics sets configuration, logging and context.
		/// </summary>
		/// <param name="configuration">The configuration.</param>
		/// <param name="loggingService">The logging-service.</param>
		/// <param name="context">The context.</param>

		public WpcSynologenRepository (
			Configuration configuration,
			ILoggingService loggingService,
			SpinitDataContext context)
			: base (context)
		{
			OnCreate ();

			Configuration = configuration;

			LoggingService = loggingService;

			TrackingOn = false;
		}

		#endregion
		
 		
		#region Create Repository

		/// <summary>
		/// Creates the repository with tracking.
		/// </summary>
		/// <param name="configuration">The configuarion.</param>
		/// <param name="loggingService">The logging service.</param>
		/// <returns>A repository</returns>

		public static WpcSynologenRepository GetWpcSynologenRepository (
			Configuration configuration,
			ILoggingService loggingService)
		{
			return new WpcSynologenRepository (
				configuration,
				loggingService);
		}

		/// <summary>
		/// Creates the repository without tracking.
		/// </summary>
		/// <param name="configuration">The configuarion.</param>
		/// <param name="loggingService">The logging service.</param>
		/// <returns>A repository</returns>

		public static WpcSynologenRepository GetWpcSynologenRepositoryNoTracking (
			Configuration configuration,
			ILoggingService loggingService)
		{
			return new WpcSynologenRepository (
				configuration,
				loggingService,
				true);
		}

		#endregion
		
		#region Search

		/// <summary>
		/// Creates a search-table.
		/// </summary>

		protected override void CreateSearchTable ()
		{
			_searchTable = new List<SearchPairs>
			{
				new SearchPairs (typeof (SynologenOpqDocumentHistory), new ESynologenOpqDocumentHistory ()),
				new SearchPairs (typeof (SynologenOpqNodeSupplierConnection), new ESynologenOpqNodeSupplierConnection ()),
				new SearchPairs (typeof (SynologenOpqDocument), new ESynologenOpqDocument ()),
				new SearchPairs (typeof (SynologenOpqDocumentType), new ESynologenOpqDocumentType ()),
				new SearchPairs (typeof (SynologenOpqFileCategory), new ESynologenOpqFileCategory ()),
				new SearchPairs (typeof (SynologenOpqFile), new ESynologenOpqFile ()),
				new SearchPairs (typeof (SynologenOpqNode), new ESynologenOpqNode ()),
			};
		}

		#endregion
		
		#region Global properties

		/// <summary>
		/// Gets or sets the configuration
		/// </summary>

		public Configuration Configuration { get; set; }

		#endregion
	}
		
}
#pragma warning restore 1591
 
