
#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Spinit's LINQ to SQL template for T4 C#
//     Generated at 10/27/2009 07:46:12
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;

using Spinit.Data.Linq;
using Spinit.Wpc.Synologen.OPQ.Data.Entities;

namespace Spinit.Wpc.Synologen.OPQ.Data
{
	[DatabaseAttribute(Name=@"dbWpcSynologen")]
	public partial class WpcSynologenDataContext : SpinitDataContext
	{
		#region Construction
	
		public WpcSynologenDataContext (string connection) :
			base(connection)
		{
			OnCreated();
		}
		
		public WpcSynologenDataContext (IDbConnection connection) :
			base(connection)
		{
			OnCreated();
		}
		
		public WpcSynologenDataContext (string connection, MappingSource mappingSource) :
			base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WpcSynologenDataContext (IDbConnection connection, MappingSource mappingSource) :
			base(connection, mappingSource)
		{
			OnCreated();
		}
		
		#endregion
		
		#region Extensibility Method Definitions
		
		partial void OnCreated();
		partial void InsertSynologenOpqDocumentHistory(EDocumentHistory instance);
		partial void UpdateSynologenOpqDocumentHistory(EDocumentHistory instance);
		partial void DeleteSynologenOpqDocumentHistory(EDocumentHistory instance);
		partial void InsertSynologenOpqNodeSupplierConnection(ENodeSupplierConnection instance);
		partial void UpdateSynologenOpqNodeSupplierConnection(ENodeSupplierConnection instance);
		partial void DeleteSynologenOpqNodeSupplierConnection(ENodeSupplierConnection instance);
		partial void InsertSynologenOpqDocument(EDocument instance);
		partial void UpdateSynologenOpqDocument(EDocument instance);
		partial void DeleteSynologenOpqDocument(EDocument instance);
		partial void InsertSynologenOpqDocumentType(EDocumentType instance);
		partial void UpdateSynologenOpqDocumentType(EDocumentType instance);
		partial void DeleteSynologenOpqDocumentType(EDocumentType instance);
		partial void InsertSynologenOpqFileCategory(EFileCategory instance);
		partial void UpdateSynologenOpqFileCategory(EFileCategory instance);
		partial void DeleteSynologenOpqFileCategory(EFileCategory instance);
		partial void InsertSynologenOpqFile(EFile instance);
		partial void UpdateSynologenOpqFile(EFile instance);
		partial void DeleteSynologenOpqFile(EFile instance);
		partial void InsertSynologenOpqNode(ENode instance);
		partial void UpdateSynologenOpqNode(ENode instance);
		partial void DeleteSynologenOpqNode(ENode instance);
		
		#endregion
		
		#region Tables

		public Table<EDocumentHistory> SynologenOpqDocumentHistories
		{
			get { return GetTable<EDocumentHistory>(); }
		}
		
		public Table<ENodeSupplierConnection> SynologenOpqNodeSupplierConnections
		{
			get { return GetTable<ENodeSupplierConnection>(); }
		}
		
		public Table<EDocument> SynologenOpqDocuments
		{
			get { return GetTable<EDocument>(); }
		}
		
		public Table<EDocumentType> SynologenOpqDocumentTypes
		{
			get { return GetTable<EDocumentType>(); }
		}
		
		public Table<EFileCategory> SynologenOpqFileCategories
		{
			get { return GetTable<EFileCategory>(); }
		}
		
		public Table<EFile> SynologenOpqFiles
		{
			get { return GetTable<EFile>(); }
		}
		
		public Table<ENode> SynologenOpqNodes
		{
			get { return GetTable<ENode>(); }
		}
		
		#endregion
	}
	
	#region Result Classes
		

	#endregion
	
}
#pragma warning restore 1591
 
