
#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Spinit's LINQ to SQL template for T4 C#
//     Generated at 10/22/2009 15:41:29
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Opq.Data
{
	public partial class WpcSynologenOpqRepository
	{
		#region On Create

		/// <summary>
		/// The on-create overriden class
		/// </summary>

		protected override sealed void OnCreate ()
		{
			/* 
				Put Manager initiation here, e.g.:
				Account = new AccountManager (this);
			*/
		}
		
		#endregion
		
		#region Managers

		/*
			Put manager getters here, e.g.:
			/// <summary>
			/// Gets the account-manager.
			/// </summary>

			public AccountManager Account { get; private set; }
		*/

		#endregion
	}
		
}
#pragma warning restore 1591
 
