//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Presentation.Site.Wpc.Synologen {
    
    public partial class ViewSettlement {
        protected System.Web.UI.WebControls.Button btnSwitchView;
        protected System.Web.UI.WebControls.Button btnMarkAsPayed;
        protected System.Web.UI.WebControls.PlaceHolder plSimpleView;
        protected System.Web.UI.WebControls.Repeater rptSettlementOrderItemsSimple;
        protected System.Web.UI.WebControls.PlaceHolder plDetailedView;
        protected System.Web.UI.WebControls.Repeater rptSettlementOrderItemsDetailed;
    }
}
