//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Presentation.Intranet.Wpc.Synologen.Yammer {


    public partial class MiniYammerFeed
    {
        
        /// <summary>
        /// yammerFeedRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater yammerFeedRepeater;

        protected global::System.Web.UI.WebControls.Literal yammerFeedContent;
    }
}
