//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Presentation.Site.Wpc.Synologen.ContractSales
{
	public partial class ViewOrder {
		protected System.Web.UI.WebControls.PlaceHolder plViewOrder;
		protected System.Web.UI.WebControls.Literal ltCompany;
		protected System.Web.UI.WebControls.Literal ltSalesPersonName;
		protected System.Web.UI.WebControls.Literal ltOrderStatus;
		protected System.Web.UI.WebControls.GridView gvOrderItemsCart;
		protected System.Web.UI.WebControls.Literal ltTotalPrice;
		protected System.Web.UI.WebControls.PlaceHolder plNoAccessMessage;
	}
}