using System;

namespace Spinit.Wpc.Forum.Enumerations {

    public enum DefaultRoles {
        Everyone = 0,
        GlobalAdministrators = 1,
        ForumAdministrators = 2,
        GlobalModerators = 3,
        ForumModerators = 4
    }

    public enum DefaultForums {
        Administrators = 1,
        Moderators = 2,
        Reporting = 3,
        DeletedPosts = 4
    }
        
    public enum Permission {
        View,
        Read,
        Post,
        Reply,
        Edit,
        Delete,
        Sticky,
        Announce,
        CreatePoll,
        Vote,
        Moderate,
        Attachment
    }

    public enum AccessControlEntry {
        NotSet  = 0x00,
        Allow   = 0x01,
        Deny    = 0x02
    }

    public enum LoginUserStatus {
        /// <summary>
        /// Username and password didn't match.
        /// </summary>
        InvalidCredentials = 0, 

        /// <summary>
        /// The user name and password are ok.
        /// </summary>
        Success = 1, 

        AccountPending = 2,

        AccountBanned = 3,

        AccountDisapproved = 4,

        /// <summary>
        /// Unknown situation possibly generated by un-syncronization beteen 
        /// data layer and business layer.
        /// </summary>
        UnknownError = 100
    }

    /// <summary>
    /// Indicates the return status for logging-in a new user.
    /// </summary>
    public enum UserAccountStatus { 

        ApprovalPending = 0,
        Approved = 1,
        Banned = 2,
        Disapproved = 3
    }
    
    public enum PasswordRecovery {
        //Email,
        Reset,
        QuestionAndAnswer
    }

    public enum UserPasswordFormat {
        ClearText = 0,
        MD5Hash = 1,
        Sha1Hash = 2,
        Encyrpted = 3
    }

    /// <summary>
    /// User banning time in days.
    /// </summary>
    public enum UserBanPeriod {
      Permanent = 55500, // ~ 150 years
      OneDay = 1,
      ThreeDays = 3,
      FiveDays = 5,
      OneWeek = 7,
      TwoWeeks = 14,
      OneMonth = 30
    }
}
