//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


public partial class Index {
    protected System.Web.UI.HtmlControls.HtmlHead Head1;
    protected System.Web.UI.HtmlControls.HtmlForm form1;
    protected Spinit.Wpc.Forum.Presentation.Site.CacheClearer ucCacheClearer;
    protected Spinit.Wpc.Base.Presentation.Site.LogoutControl ucLogoutControl;
}
