//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.3082
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace Spinit.Wpc.Synologen.Svefaktura.Svefakt2.UBL.CoreComponentParameters {
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.42")]
	[System.Serializable]
	[System.Diagnostics.DebuggerStepThrough]
	[System.ComponentModel.DesignerCategory("code")]
	[System.Xml.Serialization.XmlType(Namespace="urn:oasis:names:tc:ubl:CoreComponentParameters:1:0")]
	[System.Xml.Serialization.XmlRoot("Instance", Namespace="urn:oasis:names:tc:ubl:CoreComponentParameters:1:0", IsNullable=false)]
	public class InstanceType {
    
		private string nameField;
    
		private string codeListIDField;
    
		private string codeListAgencyIDField;
    
		private string codeListAgencyNameField;
    
		private string codeListNameField;
    
		private string codeListVersionIDField;
    
		private string codeListUniformResourceIDField;
    
		private string codeListSchemeUniformResourceIDField;
    
		private string languageIDField;
    
		/// <remarks/>
		public string Name {
			get {
				return nameField;
			}
			set {
				nameField = value;
			}
		}
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElement(DataType="normalizedString")]
		public string CodeListID {
			get {
				return codeListIDField;
			}
			set {
				codeListIDField = value;
			}
		}
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElement(DataType="normalizedString")]
		public string CodeListAgencyID {
			get {
				return codeListAgencyIDField;
			}
			set {
				codeListAgencyIDField = value;
			}
		}
    
		/// <remarks/>
		public string CodeListAgencyName {
			get {
				return codeListAgencyNameField;
			}
			set {
				codeListAgencyNameField = value;
			}
		}
    
		/// <remarks/>
		public string CodeListName {
			get {
				return codeListNameField;
			}
			set {
				codeListNameField = value;
			}
		}
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElement(DataType="normalizedString")]
		public string CodeListVersionID {
			get {
				return codeListVersionIDField;
			}
			set {
				codeListVersionIDField = value;
			}
		}
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElement(DataType="anyURI")]
		public string CodeListUniformResourceID {
			get {
				return codeListUniformResourceIDField;
			}
			set {
				codeListUniformResourceIDField = value;
			}
		}
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElement(DataType="anyURI")]
		public string CodeListSchemeUniformResourceID {
			get {
				return codeListSchemeUniformResourceIDField;
			}
			set {
				codeListSchemeUniformResourceIDField = value;
			}
		}
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElement(DataType="language")]
		public string LanguageID {
			get {
				return languageIDField;
			}
			set {
				languageIDField = value;
			}
		}
	}
}