CREATE TABLE [dbo].['Medlemmar Synologen 2011 09 10$'] (
    [ContactID]        NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Company]          NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [code]             NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Number]           FLOAT (53)     NULL,
    [Orgnumb]          NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Department]       NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Street address]   NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Street postcode]  NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Street city]      NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Postal address]   NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Postal address 2] NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Postal address 3] NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Postal postcode]  NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Postal city]      NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Postal county]    NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Postal state]     NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Postal country]   NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Phone]            NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Fax]              NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [WWW]              NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Our contact]      NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PersonID]         NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Person number]    NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MrMs]             NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Title]            NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Firstname]        NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Lastname]         NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Position]         NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Private phone]    NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Mobile phone]     NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Email]            NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Privat address]   NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Privat address 2] NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Privat address 3] NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Private postcode] NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Private city]     NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Private county]   NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Private state]    NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Private country]  NVARCHAR (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);

