CREATE TABLE [dbo].[SynologenOrderLensRecipe] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [ArticleCategoryId] INT            NOT NULL,
    [ArticleTypeId]     INT            NOT NULL,
    [ArticleSupplierId] INT            NOT NULL,
    [PowerLeft]         NVARCHAR (50)  NULL,
    [PowerRight]        NVARCHAR (50)  NULL,
    [BaseCurveLeft]     DECIMAL (5, 2) NULL,
    [BaseCurveRight]    DECIMAL (5, 2) NULL,
    [DiameterLeft]      DECIMAL (5, 2) NULL,
    [DiameterRight]     DECIMAL (5, 2) NULL,
    [AxisLeft]          NVARCHAR (50)  NULL,
    [AxisRight]         NVARCHAR (50)  NULL,
    [CylinderLeft]      NVARCHAR (50)  NULL,
    [CylinderRight]     NVARCHAR (50)  NULL,
    [AdditionLeft]      NVARCHAR (50)  NULL,
    [AdditionRight]     NVARCHAR (50)  NULL,
    [ArticleLeftId]     INT            NULL,
    [ArticleRightId]    INT            NULL,
    [QuantityLeft]      NVARCHAR (50)  NULL,
    [QuantityRight]     NVARCHAR (50)  NULL,
    CONSTRAINT [PK_SynologenOrderLensRecipe] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SynologenOrderLensRecipe_SynologenOrderArticleCategory] FOREIGN KEY ([ArticleCategoryId]) REFERENCES [dbo].[SynologenOrderArticleCategory] ([Id]),
    CONSTRAINT [FK_SynologenOrderLensRecipe_SynologenOrderArticleLeft] FOREIGN KEY ([ArticleLeftId]) REFERENCES [dbo].[SynologenOrderArticle] ([Id]),
    CONSTRAINT [FK_SynologenOrderLensRecipe_SynologenOrderArticleRight] FOREIGN KEY ([ArticleRightId]) REFERENCES [dbo].[SynologenOrderArticle] ([Id]),
    CONSTRAINT [FK_SynologenOrderLensRecipe_SynologenOrderArticleSupplier] FOREIGN KEY ([ArticleSupplierId]) REFERENCES [dbo].[SynologenOrderArticleSupplier] ([Id]),
    CONSTRAINT [FK_SynologenOrderLensRecipe_SynologenOrderArticleType] FOREIGN KEY ([ArticleTypeId]) REFERENCES [dbo].[SynologenOrderArticleType] ([Id])
);

