CREATE TABLE [dbo].[tblCourse] (
    [cId]                  INT            IDENTITY (1, 1) NOT NULL,
    [cCourseMainId]        INT            NULL,
    [cCityId]              INT            NULL,
    [cHeading]             NVARCHAR (255) NULL,
    [cSummary]             NTEXT          NULL,
    [cBody]                NTEXT          NULL,
    [cFormatedBody]        NTEXT          NULL,
    [cContactName]         NVARCHAR (50)  NULL,
    [cContactEmail]        NVARCHAR (50)  NULL,
    [cContactPhone]        NVARCHAR (15)  NULL,
    [cContactMobile]       NVARCHAR (15)  NULL,
    [cLastApplicationDate] SMALLDATETIME  NULL,
    [cPublishStartDate]    SMALLDATETIME  NULL,
    [cPublishEndDate]      SMALLDATETIME  NULL,
    [cCourseStartDate]     SMALLDATETIME  NULL,
    [cCourseEndDate]       SMALLDATETIME  NULL,
    [cMinParticipants]     INT            NULL,
    [cMaxParticipants]     INT            NULL,
    [cConfirmSubject]      NVARCHAR (255) NULL,
    [cConfirmBody]         NTEXT          NULL,
    [cReminderSubject]     NVARCHAR (255) NULL,
    [cReminderBody]        NTEXT          NULL,
    [cDaysBeforeReminder]  INT            NULL,
    [cReminderSent]        BIT            NULL,
    [cAdminEmail]          NVARCHAR (50)  NULL,
    [cContactAutoEmail]    BIT            NULL,
    [cAdminAutoEmail]      BIT            NULL,
    [cCreatedBy]           NVARCHAR (255) NULL,
    [cCreatedDate]         SMALLDATETIME  NULL,
    [cEditedBy]            NVARCHAR (255) NULL,
    [cEditedDate]          SMALLDATETIME  NULL,
    [cApprovedBy]          NVARCHAR (255) NULL,
    [cApprovedDate]        SMALLDATETIME  NULL,
    [cLockedBy]            NVARCHAR (255) NULL,
    [cLockedDate]          SMALLDATETIME  NULL,
    [cSubmissed]           INT            NULL,
    [cVisibleTo]           INT            NULL,
    CONSTRAINT [PK_tblCourses] PRIMARY KEY CLUSTERED ([cId] ASC),
    CONSTRAINT [FK_tblCourses_tblCoursesCity] FOREIGN KEY ([cCityId]) REFERENCES [dbo].[tblCourseCity] ([cId]),
    CONSTRAINT [FK_tblCourses_tblCoursesMain] FOREIGN KEY ([cCourseMainId]) REFERENCES [dbo].[tblCourseMain] ([cId])
);

