CREATE TABLE [dbo].[tblForumsStyles] (
    [StyleID]              INT          IDENTITY (1, 1) NOT NULL,
    [StyleName]            VARCHAR (30) NOT NULL,
    [StyleSheetTemplate]   VARCHAR (30) NULL,
    [BodyBackgroundColor]  VARCHAR (6)  NOT NULL,
    [BodyTextColor]        VARCHAR (6)  NOT NULL,
    [LinkVisited]          VARCHAR (6)  NOT NULL,
    [LinkHover]            VARCHAR (6)  NOT NULL,
    [LinkActive]           VARCHAR (6)  NOT NULL,
    [RowColorPrimary]      VARCHAR (6)  NOT NULL,
    [RowColorSecondary]    VARCHAR (6)  NOT NULL,
    [RowColorTertiary]     VARCHAR (6)  NOT NULL,
    [RowClassPrimary]      VARCHAR (30) NULL,
    [RowClassSecondary]    VARCHAR (30) NULL,
    [RowClassTertiary]     VARCHAR (30) NULL,
    [HeaderColorPrimary]   VARCHAR (6)  NOT NULL,
    [HeaderColorSecondary] VARCHAR (6)  NOT NULL,
    [HeaderColorTertiary]  VARCHAR (6)  NOT NULL,
    [HeaderStylePrimary]   VARCHAR (30) NULL,
    [HeaderStyleSecondary] VARCHAR (30) NULL,
    [HeaderStyleTertiary]  VARCHAR (30) NULL,
    [CellColorPrimary]     VARCHAR (6)  NOT NULL,
    [CellColorSecondary]   VARCHAR (6)  NOT NULL,
    [CellColorTertiary]    VARCHAR (6)  NOT NULL,
    [CellClassPrimary]     VARCHAR (30) NULL,
    [CellClassSecondary]   VARCHAR (30) NULL,
    [CellClassTertiary]    VARCHAR (30) NULL,
    [FontFacePrimary]      VARCHAR (30) NULL,
    [FontFaceSecondary]    VARCHAR (30) NULL,
    [FontFaceTertiary]     VARCHAR (30) NULL,
    [FontSizePrimary]      SMALLINT     NULL,
    [FontSizeSecondary]    SMALLINT     NULL,
    [FontSizeTertiary]     SMALLINT     NULL,
    [FontColorPrimary]     VARCHAR (6)  NOT NULL,
    [FontColorSecondary]   VARCHAR (6)  NOT NULL,
    [FontColorTertiary]    VARCHAR (6)  NOT NULL,
    [SpanClassPrimary]     VARCHAR (30) NULL,
    [SpanClassSecondary]   VARCHAR (30) NULL,
    [SpanClassTertiary]    VARCHAR (30) NULL,
    CONSTRAINT [PK_STYLE] PRIMARY KEY CLUSTERED ([StyleID] ASC)
);

