CREATE TABLE [dbo].[tblGallery] (
    [cId]                  INT            IDENTITY (1, 1) NOT NULL,
    [cOwner]               INT            NULL,
    [cName]                NVARCHAR (50)  NULL,
    [cHeadingStringId]     INT            NULL,
    [cDescriptionStringId] INT            NULL,
    [cGallerySpot]         INT            NULL,
    [cSpotHeight]          INT            NULL,
    [cSpotWidth]           INT            NULL,
    [cGalleryType]         INT            NULL,
    [cThumbsRows]          INT            NULL,
    [cThumbsColumns]       INT            NULL,
    [cThumbsHeight]        INT            NULL,
    [cThumbsWidth]         INT            NULL,
    [cListRowsPerPage]     INT            NULL,
    [cDefaultDirectory]    INT            CONSTRAINT [DF_tblGallery_cDefaultDirectory] DEFAULT (1) NULL,
    [cSortType]            INT            CONSTRAINT [DF_tblGallery_cSortType] DEFAULT (1) NULL,
    [cActive]              BIT            NULL,
    [cCreatedBy]           NVARCHAR (100) NULL,
    [cCreatedDate]         DATETIME       NULL,
    [cEditedBy]            NVARCHAR (100) NULL,
    [cEditedDate]          DATETIME       NULL,
    [cApprovedBy]          NVARCHAR (100) NULL,
    [cApprovedDate]        DATETIME       NULL,
    [cLockedBy]            NVARCHAR (100) NULL,
    [cLockedDate]          DATETIME       NULL,
    CONSTRAINT [PK_tblGallery] PRIMARY KEY CLUSTERED ([cId] ASC),
    CONSTRAINT [FK_tblGallery_tblBaseFile] FOREIGN KEY ([cDefaultDirectory]) REFERENCES [dbo].[tblBaseFile] ([cId])
);

