CREATE TABLE [dbo].[tblMembersContent] (
    [cId]                 INT            IDENTITY (1, 1) NOT NULL,
    [cMemberId]           INT            NOT NULL,
    [cDescription]        NVARCHAR (255) NULL,
    [cAddress]            NVARCHAR (255) NULL,
    [cZipcode]            NVARCHAR (50)  NULL,
    [cCity]               NVARCHAR (50)  NULL,
    [cPhone]              NVARCHAR (50)  NULL,
    [cFax]                NVARCHAR (50)  NULL,
    [cMobile]             NVARCHAR (50)  NULL,
    [cEmail]              NVARCHAR (50)  NULL,
    [cWww]                NVARCHAR (255) NULL,
    [cVoip]               NVARCHAR (50)  NULL,
    [cSkype]              NVARCHAR (50)  NULL,
    [cCordless]           NVARCHAR (50)  NULL,
    [cBody]               NTEXT          NULL,
    [cOther1]             NVARCHAR (100) NULL,
    [cOther2]             NVARCHAR (100) NULL,
    [cOther3]             NVARCHAR (255) NULL,
    [cContactFirst]       NVARCHAR (255) NULL,
    [cContactLast]        NVARCHAR (255) NULL,
    [cProfilePictureId]   INT            NULL,
    [cDefaultDirectoryId] INT            NULL,
    [cCreatedBy]          NVARCHAR (100) NULL,
    [cCreatedDate]        DATETIME       NULL,
    [cEditedBy]           NVARCHAR (100) NULL,
    [cEditedDate]         DATETIME       NULL,
    [cApprovedBy]         NVARCHAR (100) NULL,
    [cApprovedDate]       DATETIME       NULL,
    [cLockedBy]           NVARCHAR (100) NULL,
    [cLockedDate]         DATETIME       NULL,
    CONSTRAINT [PK_tblMembersContent] PRIMARY KEY CLUSTERED ([cId] ASC),
    CONSTRAINT [FK_tblMembersContent_tblMembers] FOREIGN KEY ([cMemberId]) REFERENCES [dbo].[tblMembers] ([cId])
);

