CREATE TABLE [dbo].[tblQuickMailMail] (
    [cId]                INT            IDENTITY (1, 1) NOT NULL,
    [cMlTpeId]           INT            NOT NULL,
    [cPriority]          INT            NOT NULL,
    [cName]              NVARCHAR (512) NOT NULL,
    [cFileName]          NVARCHAR (512) NOT NULL,
    [cFrom]              NVARCHAR (512) NOT NULL,
    [cFriendlyFrom]      NVARCHAR (512) NULL,
    [cSubject]           NVARCHAR (512) NOT NULL,
    [cUseHtml]           BIT            NOT NULL,
    [cHtmlBody]          NTEXT          NULL,
    [cUsePlain]          BIT            NOT NULL,
    [cPlainBody]         NTEXT          NULL,
    [cCharacterEncoding] NVARCHAR (20)  NOT NULL,
    [cBodyPartEncoding]  NVARCHAR (20)  NOT NULL,
    [cEmbedPictures]     BIT            NOT NULL,
    [cUseAltLink]        BIT            NOT NULL,
    [cActive]            BIT            NOT NULL,
    [cApprovedBy]        NVARCHAR (100) NULL,
    [cApprovedDate]      DATETIME       NULL,
    [cLockedBy]          NVARCHAR (100) NULL,
    [cLockedDate]        DATETIME       NULL,
    [cCreatedBy]         NVARCHAR (100) NOT NULL,
    [cCreatedDate]       DATETIME       NOT NULL,
    [cChangedBy]         NVARCHAR (100) NULL,
    [cChangedDate]       DATETIME       NULL,
    [cSendOutDate]       DATETIME       NULL,
    [cSent]              BIT            NULL,
    CONSTRAINT [PK_tblQuickMailMail] PRIMARY KEY CLUSTERED ([cId] ASC),
    CONSTRAINT [FK_tblQuickMailMail_tblQuickMailMailType] FOREIGN KEY ([cMlTpeId]) REFERENCES [dbo].[tblQuickMailMailType] ([cId])
);

