#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Spinit's LINQ to SQL template for T4 C#
//     Generated at 10/27/2009 15:35:17
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq.Expressions;

using Spinit.Data.Linq;

using Spinit.Wpc.Synologen.OPQ.Core.Entities;

namespace Spinit.Wpc.Synologen.OPQ.Data.Entities
{	
	[Table(Name=@"dbo.SynologenOpqFiles")]
	public partial class EFile : EntityBase
	{
		#region Spinit search extension
		
		/// <summary>
		/// Creates a lambda-expression for use with the data-load-option feature,
		/// </summary>
		/// <param name="property">The property to search-for.</param>
		/// <returns>A lambda-expression.</returns>

		public override LambdaExpression BuildSearchExpression (string property)
		{
			ParameterExpression parameter = Expression.Parameter (GetType (), "eFile");
			return Expression.Lambda<Func<EFile, object>> (
						Expression.Property (parameter, property),
						parameter);
		}
		
		#endregion
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(ChangeAction action);
		partial void OnCreated();
		#endregion

		#region Construction
		public EFile()
		{
			_SynologenOpqFileCategory = default(EntityRef<EFileCategory>); 
			_SynologenOpqNode = default(EntityRef<ENode>); 
			_tblBaseUser = default(EntityRef<EBaseUser>); 
			_tblBaseUser1 = default(EntityRef<EBaseUser>); 
			_tblBaseUser2 = default(EntityRef<EBaseUser>); 
			_tblBaseUser3 = default(EntityRef<EBaseUser>); 
			_tblBaseFile = default(EntityRef<EBaseFile>); 
			_tblSynologenConcern = default(EntityRef<EConcern>); 
			_tblSynologenShop = default(EntityRef<EShop>); 
			OnCreated();
		}
		#endregion

		#region Column Mappings
		partial void OnIdChanging(int value);
		partial void OnIdChanged();
		private int _Id;
		[Column(Storage=@"_Id", AutoSync=AutoSync.OnInsert, DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					OnIdChanging(value);
					SendPropertyChanging();
					_Id = value;
					SendPropertyChanged("Id");
					OnIdChanged();
				}
			}
		}
		
		partial void OnOrderChanging(int? value);
		partial void OnOrderChanged();
		private int? _Order;
		[Column (Storage = @"_Order", Name = @"[Order]", AutoSync = AutoSync.OnInsert, DbType = @"Int")]
		public int? Order
		{
			get { return _Order; }
			set {
				if (_Order != value) {
					OnOrderChanging(value);
					SendPropertyChanging();
					_Order = value;
					SendPropertyChanged("Order");
					OnOrderChanged();
				}
			}
		}
		
		partial void OnFleCatIdChanging(int value);
		partial void OnFleCatIdChanged();
		private int _FleCatId;
		[Column(Storage=@"_FleCatId", DbType=@"Int NOT NULL", CanBeNull=false)]
		public int FleCatId
		{
			get { return _FleCatId; }
			set {
				if (_FleCatId != value) {
					if (_SynologenOpqFileCategory.HasLoadedOrAssignedValue) {
						throw new ForeignKeyReferenceAlreadyHasValueException();
					}
					OnFleCatIdChanging(value);
					SendPropertyChanging();
					_FleCatId = value;
					SendPropertyChanged("FleCatId");
					OnFleCatIdChanged();
				}
			}
		}
		
		partial void OnFleIdChanging(int value);
		partial void OnFleIdChanged();
		private int _FleId;
		[Column(Storage=@"_FleId", DbType=@"Int NOT NULL", CanBeNull=false)]
		public int FleId
		{
			get { return _FleId; }
			set {
				if (_FleId != value) {
					if (_tblBaseFile.HasLoadedOrAssignedValue) {
						throw new ForeignKeyReferenceAlreadyHasValueException();
					}
					OnFleIdChanging(value);
					SendPropertyChanging();
					_FleId = value;
					SendPropertyChanged("FleId");
					OnFleIdChanged();
				}
			}
		}
		
		partial void OnNdeIdChanging(int value);
		partial void OnNdeIdChanged();
		private int _NdeId;
		[Column(Storage=@"_NdeId", DbType=@"Int NOT NULL", CanBeNull=false)]
		public int NdeId
		{
			get { return _NdeId; }
			set {
				if (_NdeId != value) {
					if (_SynologenOpqNode.HasLoadedOrAssignedValue) {
						throw new ForeignKeyReferenceAlreadyHasValueException();
					}
					OnNdeIdChanging(value);
					SendPropertyChanging();
					_NdeId = value;
					SendPropertyChanged("NdeId");
					OnNdeIdChanged();
				}
			}
		}
		
		partial void OnShpIdChanging(int? value);
		partial void OnShpIdChanged();
		private int? _ShpId;
		[Column(Storage=@"_ShpId", DbType=@"Int")]
		public int? ShpId
		{
			get { return _ShpId; }
			set {
				if (_ShpId != value) {
					if (_tblSynologenShop.HasLoadedOrAssignedValue) {
						throw new ForeignKeyReferenceAlreadyHasValueException();
					}
					OnShpIdChanging(value);
					SendPropertyChanging();
					_ShpId = value;
					SendPropertyChanged("ShpId");
					OnShpIdChanged();
				}
			}
		}
		
		partial void OnCncIdChanging(int? value);
		partial void OnCncIdChanged();
		private int? _CncId;
		[Column(Storage=@"_CncId", DbType=@"Int")]
		public int? CncId
		{
			get { return _CncId; }
			set {
				if (_CncId != value) {
					if (_tblSynologenConcern.HasLoadedOrAssignedValue) {
						throw new ForeignKeyReferenceAlreadyHasValueException();
					}
					OnCncIdChanging(value);
					SendPropertyChanging();
					_CncId = value;
					SendPropertyChanged("CncId");
					OnCncIdChanged();
				}
			}
		}
		
		partial void OnIsActiveChanging(bool value);
		partial void OnIsActiveChanged();
		private bool _IsActive;
		[Column(Storage=@"_IsActive", DbType=@"Bit NOT NULL", CanBeNull=false)]
		public bool IsActive
		{
			get { return _IsActive; }
			set {
				if (_IsActive != value) {
					OnIsActiveChanging(value);
					SendPropertyChanging();
					_IsActive = value;
					SendPropertyChanged("IsActive");
					OnIsActiveChanged();
				}
			}
		}
		
		partial void OnCreatedByIdChanging(int value);
		partial void OnCreatedByIdChanged();
		private int _CreatedById;
		[Column(Storage=@"_CreatedById", DbType=@"Int NOT NULL", CanBeNull=false)]
		public int CreatedById
		{
			get { return _CreatedById; }
			set {
				if (_CreatedById != value) {
					if (_tblBaseUser.HasLoadedOrAssignedValue) {
						throw new ForeignKeyReferenceAlreadyHasValueException();
					}
					OnCreatedByIdChanging(value);
					SendPropertyChanging();
					_CreatedById = value;
					SendPropertyChanged("CreatedById");
					OnCreatedByIdChanged();
				}
			}
		}
		
		partial void OnCreatedByNameChanging(string value);
		partial void OnCreatedByNameChanged();
		private string _CreatedByName;
		[Column(Storage=@"_CreatedByName", DbType=@"NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CreatedByName
		{
			get { return _CreatedByName; }
			set {
				if (_CreatedByName != value) {
					OnCreatedByNameChanging(value);
					SendPropertyChanging();
					_CreatedByName = value;
					SendPropertyChanged("CreatedByName");
					OnCreatedByNameChanged();
				}
			}
		}
		
		partial void OnCreatedDateChanging(DateTime value);
		partial void OnCreatedDateChanged();
		private DateTime _CreatedDate;
		[Column(Storage=@"_CreatedDate", DbType=@"DateTime NOT NULL", CanBeNull=false)]
		public DateTime CreatedDate
		{
			get { return _CreatedDate; }
			set {
				if (_CreatedDate != value) {
					OnCreatedDateChanging(value);
					SendPropertyChanging();
					_CreatedDate = value;
					SendPropertyChanged("CreatedDate");
					OnCreatedDateChanged();
				}
			}
		}
		
		partial void OnChangedByIdChanging(int? value);
		partial void OnChangedByIdChanged();
		private int? _ChangedById;
		[Column(Storage=@"_ChangedById", DbType=@"Int")]
		public int? ChangedById
		{
			get { return _ChangedById; }
			set {
				if (_ChangedById != value) {
					if (_tblBaseUser1.HasLoadedOrAssignedValue) {
						throw new ForeignKeyReferenceAlreadyHasValueException();
					}
					OnChangedByIdChanging(value);
					SendPropertyChanging();
					_ChangedById = value;
					SendPropertyChanged("ChangedById");
					OnChangedByIdChanged();
				}
			}
		}
		
		partial void OnChangedByNameChanging(string value);
		partial void OnChangedByNameChanged();
		private string _ChangedByName;
		[Column(Storage=@"_ChangedByName", DbType=@"NVarChar(100)")]
		public string ChangedByName
		{
			get { return _ChangedByName; }
			set {
				if (_ChangedByName != value) {
					OnChangedByNameChanging(value);
					SendPropertyChanging();
					_ChangedByName = value;
					SendPropertyChanged("ChangedByName");
					OnChangedByNameChanged();
				}
			}
		}
		
		partial void OnChangedDateChanging(DateTime? value);
		partial void OnChangedDateChanged();
		private DateTime? _ChangedDate;
		[Column(Storage=@"_ChangedDate", DbType=@"DateTime")]
		public DateTime? ChangedDate
		{
			get { return _ChangedDate; }
			set {
				if (_ChangedDate != value) {
					OnChangedDateChanging(value);
					SendPropertyChanging();
					_ChangedDate = value;
					SendPropertyChanged("ChangedDate");
					OnChangedDateChanged();
				}
			}
		}
		
		partial void OnApprovedByIdChanging(int? value);
		partial void OnApprovedByIdChanged();
		private int? _ApprovedById;
		[Column(Storage=@"_ApprovedById", DbType=@"Int")]
		public int? ApprovedById
		{
			get { return _ApprovedById; }
			set {
				if (_ApprovedById != value) {
					if (_tblBaseUser2.HasLoadedOrAssignedValue) {
						throw new ForeignKeyReferenceAlreadyHasValueException();
					}
					OnApprovedByIdChanging(value);
					SendPropertyChanging();
					_ApprovedById = value;
					SendPropertyChanged("ApprovedById");
					OnApprovedByIdChanged();
				}
			}
		}
		
		partial void OnApprovedByNameChanging(string value);
		partial void OnApprovedByNameChanged();
		private string _ApprovedByName;
		[Column(Storage=@"_ApprovedByName", DbType=@"NVarChar(100)")]
		public string ApprovedByName
		{
			get { return _ApprovedByName; }
			set {
				if (_ApprovedByName != value) {
					OnApprovedByNameChanging(value);
					SendPropertyChanging();
					_ApprovedByName = value;
					SendPropertyChanged("ApprovedByName");
					OnApprovedByNameChanged();
				}
			}
		}
		
		partial void OnApprovedDateChanging(DateTime? value);
		partial void OnApprovedDateChanged();
		private DateTime? _ApprovedDate;
		[Column(Storage=@"_ApprovedDate", DbType=@"DateTime")]
		public DateTime? ApprovedDate
		{
			get { return _ApprovedDate; }
			set {
				if (_ApprovedDate != value) {
					OnApprovedDateChanging(value);
					SendPropertyChanging();
					_ApprovedDate = value;
					SendPropertyChanged("ApprovedDate");
					OnApprovedDateChanged();
				}
			}
		}
		
		partial void OnLockedByIdChanging(int? value);
		partial void OnLockedByIdChanged();
		private int? _LockedById;
		[Column(Storage=@"_LockedById", DbType=@"Int")]
		public int? LockedById
		{
			get { return _LockedById; }
			set {
				if (_LockedById != value) {
					if (_tblBaseUser3.HasLoadedOrAssignedValue) {
						throw new ForeignKeyReferenceAlreadyHasValueException();
					}
					OnLockedByIdChanging(value);
					SendPropertyChanging();
					_LockedById = value;
					SendPropertyChanged("LockedById");
					OnLockedByIdChanged();
				}
			}
		}
		
		partial void OnLockedByNameChanging(string value);
		partial void OnLockedByNameChanged();
		private string _LockedByName;
		[Column(Storage=@"_LockedByName", DbType=@"NVarChar(100)")]
		public string LockedByName
		{
			get { return _LockedByName; }
			set {
				if (_LockedByName != value) {
					OnLockedByNameChanging(value);
					SendPropertyChanging();
					_LockedByName = value;
					SendPropertyChanged("LockedByName");
					OnLockedByNameChanged();
				}
			}
		}
		
		partial void OnLockedDateChanging(DateTime? value);
		partial void OnLockedDateChanged();
		private DateTime? _LockedDate;
		[Column(Storage=@"_LockedDate", DbType=@"DateTime")]
		public DateTime? LockedDate
		{
			get { return _LockedDate; }
			set {
				if (_LockedDate != value) {
					OnLockedDateChanging(value);
					SendPropertyChanging();
					_LockedDate = value;
					SendPropertyChanged("LockedDate");
					OnLockedDateChanged();
				}
			}
		}
		
		#endregion
		
		#region Associations
		private EntityRef<EFileCategory> _SynologenOpqFileCategory;
		[Association(Name=@"SynologenOpqFileCategory_SynologenOpqFile", Storage=@"_SynologenOpqFileCategory", ThisKey=@"FleCatId", OtherKey=@"Id", IsForeignKey=true)]
		public EFileCategory FileCategory
		{
			get {
				return _SynologenOpqFileCategory.Entity;
			}
			set {
				EFileCategory previousValue = _SynologenOpqFileCategory.Entity;
				if ((previousValue != value) || (!_SynologenOpqFileCategory.HasLoadedOrAssignedValue)) {
					SendPropertyChanging();
					if (previousValue != null) {
						_SynologenOpqFileCategory.Entity = null;
						previousValue.Files.Remove(this);
					}
					_SynologenOpqFileCategory.Entity = value;
					if (value != null) {
						value.Files.Add(this);
						_FleCatId = value.Id;
					}
					else {
						_FleCatId = default(int);
					}
					SendPropertyChanged("FileCategory");
				}
			}
		}

		private EntityRef<ENode> _SynologenOpqNode;
		[Association(Name=@"SynologenOpqNode_SynologenOpqFile", Storage=@"_SynologenOpqNode", ThisKey=@"NdeId", OtherKey=@"Id", IsForeignKey=true)]
		public ENode Node
		{
			get {
				return _SynologenOpqNode.Entity;
			}
			set {
				ENode previousValue = _SynologenOpqNode.Entity;
				if ((previousValue != value) || (!_SynologenOpqNode.HasLoadedOrAssignedValue)) {
					SendPropertyChanging();
					if (previousValue != null) {
						_SynologenOpqNode.Entity = null;
						previousValue.Files.Remove(this);
					}
					_SynologenOpqNode.Entity = value;
					if (value != null) {
						value.Files.Add(this);
						_NdeId = value.Id;
					}
					else {
						_NdeId = default(int);
					}
					SendPropertyChanged("Node");
				}
			}
		}

		private EntityRef<EBaseUser> _tblBaseUser;
		[Association(Name=@"tblBaseUser_SynologenOpqFile", Storage=@"_tblBaseUser", ThisKey=@"CreatedById", OtherKey=@"Id", IsForeignKey=true)]
		public EBaseUser CreatedBy
		{
			get {
				return _tblBaseUser.Entity;
			}
			set {
				EBaseUser previousValue = _tblBaseUser.Entity;
				if ((previousValue != value) || (!_tblBaseUser.HasLoadedOrAssignedValue)) {
					SendPropertyChanging();
					if (previousValue != null) {
						_tblBaseUser.Entity = null;
						previousValue.CreatedByFiles.Remove(this);
					}
					_tblBaseUser.Entity = value;
					if (value != null) {
						value.CreatedByFiles.Add(this);
						_CreatedById = value.Id;
					}
					else {
						_CreatedById = default(int);
					}
					SendPropertyChanged("CreatedBy");
				}
			}
		}

		private EntityRef<EBaseUser> _tblBaseUser1;
		[Association(Name=@"tblBaseUser_SynologenOpqFile1", Storage=@"_tblBaseUser1", ThisKey=@"ChangedById", OtherKey=@"Id", IsForeignKey=true)]
		public EBaseUser ChangedBy
		{
			get {
				return _tblBaseUser1.Entity;
			}
			set {
				EBaseUser previousValue = _tblBaseUser1.Entity;
				if ((previousValue != value) || (!_tblBaseUser1.HasLoadedOrAssignedValue)) {
					SendPropertyChanging();
					if (previousValue != null) {
						_tblBaseUser1.Entity = null;
						previousValue.ChangedByFiles.Remove(this);
					}
					_tblBaseUser1.Entity = value;
					if (value != null) {
						value.ChangedByFiles.Add(this);
						_ChangedById = value.Id;
					}
					else {
						_ChangedById = default(int?);
					}
					SendPropertyChanged("ChagnedBy");
				}
			}
		}

		private EntityRef<EBaseUser> _tblBaseUser2;
		[Association(Name=@"tblBaseUser_SynologenOpqFile2", Storage=@"_tblBaseUser2", ThisKey=@"ApprovedById", OtherKey=@"Id", IsForeignKey=true)]
		public EBaseUser ApprovedBy
		{
			get {
				return _tblBaseUser2.Entity;
			}
			set {
				EBaseUser previousValue = _tblBaseUser2.Entity;
				if ((previousValue != value) || (!_tblBaseUser2.HasLoadedOrAssignedValue)) {
					SendPropertyChanging();
					if (previousValue != null) {
						_tblBaseUser2.Entity = null;
						previousValue.ApprovedByFiles.Remove(this);
					}
					_tblBaseUser2.Entity = value;
					if (value != null) {
						value.ApprovedByFiles.Add(this);
						_ApprovedById = value.Id;
					}
					else {
						_ApprovedById = default(int?);
					}
					SendPropertyChanged("ApprovedBy");
				}
			}
		}

		private EntityRef<EBaseUser> _tblBaseUser3;
		[Association(Name=@"tblBaseUser_SynologenOpqFile3", Storage=@"_tblBaseUser3", ThisKey=@"LockedById", OtherKey=@"Id", IsForeignKey=true)]
		public EBaseUser LockedBy
		{
			get {
				return _tblBaseUser3.Entity;
			}
			set {
				EBaseUser previousValue = _tblBaseUser3.Entity;
				if ((previousValue != value) || (!_tblBaseUser3.HasLoadedOrAssignedValue)) {
					SendPropertyChanging();
					if (previousValue != null) {
						_tblBaseUser3.Entity = null;
						previousValue.LockedByFiles.Remove(this);
					}
					_tblBaseUser3.Entity = value;
					if (value != null) {
						value.LockedByFiles.Add(this);
						_LockedById = value.Id;
					}
					else {
						_LockedById = default(int?);
					}
					SendPropertyChanged("LockedBy");
				}
			}
		}

		private EntityRef<EBaseFile> _tblBaseFile;
		[Association(Name=@"tblBaseFile_SynologenOpqFile", Storage=@"_tblBaseFile", ThisKey=@"FleId", OtherKey=@"Id", IsForeignKey=true)]
		public EBaseFile BaseFile
		{
			get {
				return _tblBaseFile.Entity;
			}
			set {
				EBaseFile previousValue = _tblBaseFile.Entity;
				if ((previousValue != value) || (!_tblBaseFile.HasLoadedOrAssignedValue)) {
					SendPropertyChanging();
					if (previousValue != null) {
						_tblBaseFile.Entity = null;
						previousValue.Files.Remove(this);
					}
					_tblBaseFile.Entity = value;
					if (value != null) {
						value.Files.Add(this);
						_FleId = value.Id;
					}
					else {
						_FleId = default(int);
					}
					SendPropertyChanged("BaseFile");
				}
			}
		}

		private EntityRef<EConcern> _tblSynologenConcern;
		[Association(Name=@"tblSynologenConcern_SynologenOpqFile", Storage=@"_tblSynologenConcern", ThisKey=@"CncId", OtherKey=@"Id", IsForeignKey=true)]
		public EConcern Concern
		{
			get {
				return _tblSynologenConcern.Entity;
			}
			set {
				EConcern previousValue = _tblSynologenConcern.Entity;
				if ((previousValue != value) || (!_tblSynologenConcern.HasLoadedOrAssignedValue)) {
					SendPropertyChanging();
					if (previousValue != null) {
						_tblSynologenConcern.Entity = null;
						previousValue.Files.Remove(this);
					}
					_tblSynologenConcern.Entity = value;
					if (value != null) {
						value.Files.Add(this);
						_CncId = value.Id;
					}
					else {
						_CncId = default(int?);
					}
					SendPropertyChanged("Concern");
				}
			}
		}

		private EntityRef<EShop> _tblSynologenShop;
		[Association(Name=@"tblSynologenShop_SynologenOpqFile", Storage=@"_tblSynologenShop", ThisKey=@"ShpId", OtherKey=@"Id", IsForeignKey=true)]
		public EShop Shop
		{
			get {
				return _tblSynologenShop.Entity;
			}
			set {
				EShop previousValue = _tblSynologenShop.Entity;
				if ((previousValue != value) || (!_tblSynologenShop.HasLoadedOrAssignedValue)) {
					SendPropertyChanging();
					if (previousValue != null) {
						_tblSynologenShop.Entity = null;
						previousValue.Files.Remove(this);
					}
					_tblSynologenShop.Entity = value;
					if (value != null) {
						value.Files.Add(this);
						_ShpId = value.Id;
					}
					else {
						_ShpId = default(int?);
					}
					SendPropertyChanged("Shop");
				}
			}
		}

		#endregion

		#region Converters
		
		/// <summary>
		/// Converts from EFile to File.
		/// </summary>
		/// <param name="eFile">The EFile.</param>
		/// <returns>The converted File.</returns>

		public static File Convert (EFile eFile)
		{
			File file = new File
			{
				Id = eFile.Id,
				Order = eFile.Order,
				FleCatId = eFile.FleCatId,
				FleId = eFile.FleId,
				NdeId = eFile.NdeId,
				ShpId = eFile.ShpId,
				CncId = eFile.CncId,
				IsActive = eFile.IsActive,
				CreatedById = eFile.CreatedById,
				CreatedByName = eFile.CreatedByName,
				CreatedDate = eFile.CreatedDate,
				ChangedById = eFile.ChangedById,
				ChangedByName = eFile.ChangedByName,
				ChangedDate = eFile.ChangedDate,
				ApprovedById = eFile.ApprovedById,
				ApprovedByName = eFile.ApprovedByName,
				ApprovedDate = eFile.ApprovedDate,
				LockedById = eFile.LockedById,
				LockedByName = eFile.LockedByName,
				LockedDate = eFile.LockedDate,
			};
			
			return file;
		}
		
		/// <summary>
		/// Converts from File to EFile.
		/// </summary>
		/// <param name="file">The File.</param>
		/// <returns>The converted EFile.</returns>

		public static EFile Convert (File file)
		{		
			return new EFile
			{
				Id = file.Id,
				Order = file.Order,
				FleCatId = file.FleCatId,
				FleId = file.FleId,
				NdeId = file.NdeId,
				ShpId = file.ShpId,
				CncId = file.CncId,
				IsActive = file.IsActive,
				CreatedById = file.CreatedById,
				CreatedByName = file.CreatedByName,
				CreatedDate = file.CreatedDate,
				ChangedById = file.ChangedById,
				ChangedByName = file.ChangedByName,
				ChangedDate = file.ChangedDate,
				ApprovedById = file.ApprovedById,
				ApprovedByName = file.ApprovedByName,
				ApprovedDate = file.ApprovedDate,
				LockedById = file.LockedById,
				LockedByName = file.LockedByName,
				LockedDate = file.LockedDate,
			};
		}

		#endregion
	}
}
#pragma warning restore 1591
