#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Spinit's LINQ to SQL template for T4 C#
//     Generated at 10/27/2009 15:39:30
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq.Expressions;

using Spinit.Data.Linq;

using Spinit.Wpc.Synologen.OPQ.Core.Entities;

namespace Spinit.Wpc.Synologen.OPQ.Data.Entities
{	
	[Table(Name=@"dbo.tblSynologenShopCategoryMemberCategoryConnection")]
	public partial class EShopCategoryMemberCategoryConnection : EntityBase
	{
		#region Spinit search extension
		
		/// <summary>
		/// Creates a lambda-expression for use with the data-load-option feature,
		/// </summary>
		/// <param name="property">The property to search-for.</param>
		/// <returns>A lambda-expression.</returns>

		public override LambdaExpression BuildSearchExpression (string property)
		{
			ParameterExpression parameter = Expression.Parameter (GetType (), "eShopCategoryMemberCategoryConnection");
			return Expression.Lambda<Func<EShopCategoryMemberCategoryConnection, object>> (
						Expression.Property (parameter, property),
						parameter);
		}
		
		#endregion
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(ChangeAction action);
		partial void OnCreated();
		#endregion

		#region Construction
		public EShopCategoryMemberCategoryConnection()
		{
			_tblSynologenShopCategory = default(EntityRef<EShopCategory>); 
			_tblMemberCategory = default(EntityRef<EMemberCategory>); 
			OnCreated();
		}
		#endregion

		#region Column Mappings
		partial void OnShopCategoryIdChanging(int value);
		partial void OnShopCategoryIdChanged();
		private int _ShopCategoryId;
		[Column(Storage=@"_ShopCategoryId", Name=@"cShopCategoryId", DbType=@"Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int ShopCategoryId
		{
			get { return _ShopCategoryId; }
			set {
				if (_ShopCategoryId != value) {
					if (_tblSynologenShopCategory.HasLoadedOrAssignedValue) {
						throw new ForeignKeyReferenceAlreadyHasValueException();
					}
					OnShopCategoryIdChanging(value);
					SendPropertyChanging();
					_ShopCategoryId = value;
					SendPropertyChanged("ShopCategoryId");
					OnShopCategoryIdChanged();
				}
			}
		}
		
		partial void OnMemberCategoryIdChanging(int value);
		partial void OnMemberCategoryIdChanged();
		private int _MemberCategoryId;
		[Column(Storage=@"_MemberCategoryId", Name=@"cMemberCategoryId", DbType=@"Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int MemberCategoryId
		{
			get { return _MemberCategoryId; }
			set {
				if (_MemberCategoryId != value) {
					if (_tblMemberCategory.HasLoadedOrAssignedValue) {
						throw new ForeignKeyReferenceAlreadyHasValueException();
					}
					OnMemberCategoryIdChanging(value);
					SendPropertyChanging();
					_MemberCategoryId = value;
					SendPropertyChanged("MemberCategoryId");
					OnMemberCategoryIdChanged();
				}
			}
		}
		
		#endregion
		
		#region Associations
		private EntityRef<EShopCategory> _tblSynologenShopCategory;
		[Association(Name=@"tblSynologenShopCategory_tblSynologenShopCategoryMemberCategoryConnection", Storage=@"_tblSynologenShopCategory", ThisKey=@"ShopCategoryId", OtherKey=@"Id", IsForeignKey=true)]
		public EShopCategory ShopCategory
		{
			get {
				return _tblSynologenShopCategory.Entity;
			}
			set {
				EShopCategory previousValue = _tblSynologenShopCategory.Entity;
				if ((previousValue != value) || (!_tblSynologenShopCategory.HasLoadedOrAssignedValue)) {
					SendPropertyChanging();
					if (previousValue != null) {
						_tblSynologenShopCategory.Entity = null;
						previousValue.ShopCategoryMemberCategoryConnections.Remove(this);
					}
					_tblSynologenShopCategory.Entity = value;
					if (value != null) {
						value.ShopCategoryMemberCategoryConnections.Add(this);
						_ShopCategoryId = value.Id;
					}
					else {
						_ShopCategoryId = default(int);
					}
					SendPropertyChanged("ShopCategory");
				}
			}
		}

		private EntityRef<EMemberCategory> _tblMemberCategory;
		[Association(Name=@"tblMemberCategory_tblSynologenShopCategoryMemberCategoryConnection", Storage=@"_tblMemberCategory", ThisKey=@"MemberCategoryId", OtherKey=@"Id", IsForeignKey=true)]
		public EMemberCategory MemberCategory
		{
			get {
				return _tblMemberCategory.Entity;
			}
			set {
				EMemberCategory previousValue = _tblMemberCategory.Entity;
				if ((previousValue != value) || (!_tblMemberCategory.HasLoadedOrAssignedValue)) {
					SendPropertyChanging();
					if (previousValue != null) {
						_tblMemberCategory.Entity = null;
						previousValue.ShopCategoryMemberCategoryConnections.Remove(this);
					}
					_tblMemberCategory.Entity = value;
					if (value != null) {
						value.ShopCategoryMemberCategoryConnections.Add(this);
						_MemberCategoryId = value.Id;
					}
					else {
						_MemberCategoryId = default(int);
					}
					SendPropertyChanged("MemberCategory");
				}
			}
		}

		#endregion

		#region Converters
		
		/// <summary>
		/// Converts from EShopCategoryMemberCategoryConnection to ShopCategoryMemberCategoryConnection.
		/// </summary>
		/// <param name="eShopCategoryMemberCategoryConnection">The EShopCategoryMemberCategoryConnection.</param>
		/// <returns>The converted ShopCategoryMemberCategoryConnection.</returns>

		public static ShopCategoryMemberCategoryConnection Convert (EShopCategoryMemberCategoryConnection eShopCategoryMemberCategoryConnection)
		{
			ShopCategoryMemberCategoryConnection shopCategoryMemberCategoryConnection = new ShopCategoryMemberCategoryConnection
			{
				ShopCategoryId = eShopCategoryMemberCategoryConnection.ShopCategoryId,
				MemberCategoryId = eShopCategoryMemberCategoryConnection.MemberCategoryId,
			};
			
			return shopCategoryMemberCategoryConnection;
		}
		
		/// <summary>
		/// Converts from ShopCategoryMemberCategoryConnection to EShopCategoryMemberCategoryConnection.
		/// </summary>
		/// <param name="shopCategoryMemberCategoryConnection">The ShopCategoryMemberCategoryConnection.</param>
		/// <returns>The converted EShopCategoryMemberCategoryConnection.</returns>

		public static EShopCategoryMemberCategoryConnection Convert (ShopCategoryMemberCategoryConnection shopCategoryMemberCategoryConnection)
		{		
			return new EShopCategoryMemberCategoryConnection
			{
				ShopCategoryId = shopCategoryMemberCategoryConnection.ShopCategoryId,
				MemberCategoryId = shopCategoryMemberCategoryConnection.MemberCategoryId,
			};
		}

		#endregion
	}
}
#pragma warning restore 1591
