#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Spinit's LINQ to SQL template for T4 C#
//     Generated at 10/22/2009 15:41:29
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq.Expressions;

using Spinit.Data.Linq;

using Spinit.Wpc.Synologen.Opq.Core.Entities;

namespace Spinit.Wpc.Synologen.Opq.Data.Entities
{	
	[Table(Name=@"dbo.SynologenOpqNodeSupplierConnections")]
	public partial class ESynologenOpqNodeSupplierConnection : EntityBase
	{
		#region Spinit search extension
		
		/// <summary>
		/// Creates a lambda-expression for use with the data-load-option feature,
		/// </summary>
		/// <param name="property">The property to search-for.</param>
		/// <returns>A lambda-expression.</returns>

		public override LambdaExpression BuildSearchExpression (string property)
		{
			ParameterExpression parameter = Expression.Parameter (GetType (), "eSynologenOpqNodeSupplierConnection");
			return Expression.Lambda<Func<ESynologenOpqNodeSupplierConnection, object>> (
						Expression.Property (parameter, property),
						parameter);
		}
		
		#endregion
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(ChangeAction action);
		partial void OnCreated();
		#endregion

		#region Construction
		public ESynologenOpqNodeSupplierConnection()
		{
			_SynologenOpqNode = default(EntityRef<ESynologenOpqNode>); 
			OnCreated();
		}
		#endregion

		#region Column Mappings
		partial void OnNdeIdChanging(int value);
		partial void OnNdeIdChanged();
		private int _NdeId;
		[Column(Storage=@"_NdeId", DbType=@"Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int NdeId
		{
			get { return _NdeId; }
			set {
				if (_NdeId != value) {
					if (_SynologenOpqNode.HasLoadedOrAssignedValue) {
						throw new ForeignKeyReferenceAlreadyHasValueException();
					}
					OnNdeIdChanging(value);
					SendPropertyChanging();
					_NdeId = value;
					SendPropertyChanged("NdeId");
					OnNdeIdChanged();
				}
			}
		}
		
		partial void OnSupIdChanging(int value);
		partial void OnSupIdChanged();
		private int _SupId;
		[Column(Storage=@"_SupId", DbType=@"Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int SupId
		{
			get { return _SupId; }
			set {
				if (_SupId != value) {
					OnSupIdChanging(value);
					SendPropertyChanging();
					_SupId = value;
					SendPropertyChanged("SupId");
					OnSupIdChanged();
				}
			}
		}
		
		#endregion
		
		#region Associations
		private EntityRef<ESynologenOpqNode> _SynologenOpqNode;
		[Association(Name=@"SynologenOpqNode_SynologenOpqNodeSupplierConnection", Storage=@"_SynologenOpqNode", ThisKey=@"NdeId", OtherKey=@"Id", IsForeignKey=true)]
		public ESynologenOpqNode SynologenOpqNode
		{
			get {
				return _SynologenOpqNode.Entity;
			}
			set {
				ESynologenOpqNode previousValue = _SynologenOpqNode.Entity;
				if ((previousValue != value) || (!_SynologenOpqNode.HasLoadedOrAssignedValue)) {
					SendPropertyChanging();
					if (previousValue != null) {
						_SynologenOpqNode.Entity = null;
						previousValue.SynologenOpqNodeSupplierConnections.Remove(this);
					}
					_SynologenOpqNode.Entity = value;
					if (value != null) {
						value.SynologenOpqNodeSupplierConnections.Add(this);
						_NdeId = value.Id;
					}
					else {
						_NdeId = default(int);
					}
					SendPropertyChanged("SynologenOpqNode");
				}
			}
		}

		#endregion

		#region Converters
		
		/// <summary>
		/// Converts from ESynologenOpqNodeSupplierConnection to SynologenOpqNodeSupplierConnection.
		/// </summary>
		/// <param name="eSynologenOpqNodeSupplierConnection">The ESynologenOpqNodeSupplierConnection.</param>
		/// <returns>The converted SynologenOpqNodeSupplierConnection.</returns>

		public SynologenOpqNodeSupplierConnection ToEntity (ESynologenOpqNodeSupplierConnection eSynologenOpqNodeSupplierConnection)
		{
			SynologenOpqNodeSupplierConnection synologenOpqNodeSupplierConnection = new SynologenOpqNodeSupplierConnection
			{
				NdeId = eSynologenOpqNodeSupplierConnection.NdeId,
				SupId = eSynologenOpqNodeSupplierConnection.SupId,
			};
			
			return synologenOpqNodeSupplierConnection;
		}
		
		/// <summary>
		/// Converts from SynologenOpqNodeSupplierConnection to ESynologenOpqNodeSupplierConnection.
		/// </summary>
		/// <param name="synologenOpqNodeSupplierConnection">The SynologenOpqNodeSupplierConnection.</param>
		/// <returns>The converted ESynologenOpqNodeSupplierConnection.</returns>

		public ESynologenOpqNodeSupplierConnection ToEntity (SynologenOpqNodeSupplierConnection synologenOpqNodeSupplierConnection)
		{		
			return new ESynologenOpqNodeSupplierConnection
			{
				NdeId = synologenOpqNodeSupplierConnection.NdeId,
				SupId = synologenOpqNodeSupplierConnection.SupId,
			};
		}

		#endregion
	}
}
#pragma warning restore 1591
