//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.OPQ.Site {
    
    
    public partial class _Default {
        
        /// <summary>
        /// OpqMenu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spinit.Wpc.Synologen.OPQ.Site.Wpc.Synologen.OpqMenu OpqMenu1;
        
        /// <summary>
        /// OpqMenu2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spinit.Wpc.Synologen.OPQ.Site.Wpc.Synologen.OpqMenu OpqMenu2;
        
        /// <summary>
        /// OpqStartPage1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spinit.Wpc.Synologen.OPQ.Site.Wpc.Synologen.OpqStartPage OpqStartPage1;
    }
}
