#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Spinit's LINQ to SQL template for T4 C#
//     Generated at 06/04/2012 12:03:11
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Spinit.Wpc.Synologen.OPQ.Core.Entities
{	
	public class BaseUser
	{
		#region Column Mappings
		
		public int Id { get; set; }
		
		public string UserName { get; set; }
		
		public string Password { get; set; }
		
		public string FirstName { get; set; }
		
		public string LastName { get; set; }
		
		public string Email { get; set; }
		
		public int? DefaultLocation { get; set; }
		
		public bool Active { get; set; }
		
		public string CreatedBy { get; set; }
		
		public DateTime? CreatedDate { get; set; }
		
		public string ChangedBy { get; set; }
		
		public DateTime? ChangedDate { get; set; }
		
		#endregion
		
		#region Associations
		
		public List<FileCategory> FileCategories { get; set; }
		
		public List<FileCategory> FileCategories1 { get; set; }
		
		public List<Node> Nodes { get; set; }
		
		public List<Node> Nodes1 { get; set; }
		
		public List<Node> Nodes2 { get; set; }
		
		public List<Node> Nodes3 { get; set; }
		
		public List<NodeSupplierConnection> NodeSupplierConnections { get; set; }
		
		public List<File> Files { get; set; }
		
		public List<File> Files1 { get; set; }
		
		public List<File> Files2 { get; set; }
		
		public List<File> Files3 { get; set; }
		
		public List<DocumentHistory> DocumentHistories { get; set; }
		
		public List<Document> Documents { get; set; }
		
		public List<Document> Documents1 { get; set; }
		
		public List<Document> Documents2 { get; set; }
		
		public List<Document> Documents3 { get; set; }
		
		public List<MemberUserConnection> MemberUserConnections { get; set; }
		
		public BaseLocation BaseLocation { get; set; }
		
		#endregion
		
		#region Overrides
		
		/// <summary>
		/// Returnes the string representation of this class.
		/// </summary>
		/// <returns>The string.</returns>

		public override string ToString ()
		{
			string str = string.Empty;
				 				  
			str += string.Concat (UserName, " ") ?? string.Empty;
				  
			str += string.Concat (Password, " ") ?? string.Empty;
				  
			str += string.Concat (FirstName, " ") ?? string.Empty;
				  
			str += string.Concat (LastName, " ") ?? string.Empty;
				  
			str += string.Concat (Email, " ") ?? string.Empty;
				 				 				  
			str += string.Concat (CreatedBy, " ") ?? string.Empty;
				 				  
			str += string.Concat (ChangedBy, " ") ?? string.Empty;
				 
			return str.Length > 1 ? str.Substring(0, str.Length - 1) : str;
		}		
		
		/// <summary>
		/// Overrides the equals base method.
		/// </summary>
		/// <param name="o">The compare object.</param>
		/// <returns>If match, true.</returns>

		public override bool Equals (object o)
		{
			if (!(o is BaseUser )) {
				return false;
			}

			BaseUser eq = o as BaseUser;

			return Id == eq.Id;
		}

		/// <summary>
		/// Overrides the GetHashCode base method.
		/// </summary>
		/// <returns>The hash-code for this object.</returns>

		public override int GetHashCode ()
		{
			return Id.GetHashCode ();
		}

		#endregion
	}
}
#pragma warning restore 1591
