#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Spinit's LINQ to SQL template for T4 C#
//     Generated at 06/07/2012 10:51:23
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Spinit.Wpc.Synologen.OPQ.Core.Entities
{	
	public class ForumUser
	{
		#region Column Mappings
		
		public int UserID { get; set; }
		
		public string UserName { get; set; }
		
		public string Password { get; set; }
		
		public short PasswordFormat { get; set; }
		
		public string Salt { get; set; }
		
		public string PasswordQuestion { get; set; }
		
		public string PasswordAnswer { get; set; }
		
		public string Email { get; set; }
		
		public DateTime DateCreated { get; set; }
		
		public DateTime LastLogin { get; set; }
		
		public DateTime LastActivity { get; set; }
		
		public string LastAction { get; set; }
		
		public short UserAccountStatus { get; set; }
		
		public bool IsAnonymous { get; set; }
		
		public bool ForceLogin { get; set; }
		
		public string AppUserToken { get; set; }
		
		#endregion
	}
}
#pragma warning restore 1591
