#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Spinit's LINQ to SQL template for T4 C#
//     Generated at 11/16/2009 09:19:49
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Spinit.Wpc.Synologen.OPQ.Core.Entities
{	
	public class MemberUserConnection
	{
		#region Column Mappings
		
		public int MemberId { get; set; }
		
		public int UserId { get; set; }
		
		#endregion
		
		#region Associations
		
		public Member Member { get; set; }
		
		public BaseUser BaseUser { get; set; }
		
		#endregion
		
		#region Overrides
		
		/// <summary>
		/// Returnes the string representation of this class.
		/// </summary>
		/// <returns>The string.</returns>

		public override string ToString ()
		{
			string str = string.Empty;
				 				 
			return str.Length > 1 ? str.Substring(0, str.Length - 1) : str;
		}		
		
		/// <summary>
		/// Overrides the equals base method.
		/// </summary>
		/// <param name="o">The compare object.</param>
		/// <returns>If match, true.</returns>

		public override bool Equals (object o)
		{
			if (!(o is MemberUserConnection )) {
				return false;
			}

			MemberUserConnection eq = o as MemberUserConnection;

			return MemberId == eq.MemberId && UserId == eq.UserId;
		}

		/// <summary>
		/// Overrides the GetHashCode base method.
		/// </summary>
		/// <returns>The hash-code for this object.</returns>

		public override int GetHashCode ()
		{
			return MemberId.GetHashCode () + UserId.GetHashCode ();
		}

		#endregion
	}
}
#pragma warning restore 1591
