//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.WebService.App_GlobalResources{
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option or rebuild the Visual Studio project.
	[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCode()]
	[global::System.Runtime.CompilerServices.CompilerGenerated()]
	internal class ServiceResources {
        
		private static global::System.Resources.ResourceManager resourceMan;
        
		private static global::System.Globalization.CultureInfo resourceCulture;
        
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ServiceResources() {
		}
        
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ServiceResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
        
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to Ett fel har uppstått i Synologen Webservice.
		/// </summary>
		internal static string ErrorEmailSubject {
			get {
				return ResourceManager.GetString("ErrorEmailSubject", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to Faktura {0} skickades via FTP: {1}.
		/// </summary>
		internal static string InvoiceSentHistoryMessage {
			get {
				return ResourceManager.GetString("InvoiceSentHistoryMessage", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to Ordern importerades till visma och fick ordernr {0}. Pris inkl moms {1}, exkl moms {2}..
		/// </summary>
		internal static string OrderAddedToVismaHistoryMessage {
			get {
				return ResourceManager.GetString("OrderAddedToVismaHistoryMessage", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to Faktura-status för faktura {0} uppdaterades..
		/// </summary>
		internal static string OrderStatusUpdatedHistoryMessage {
			get {
				return ResourceManager.GetString("OrderStatusUpdatedHistoryMessage", resourceCulture);
			}
		}
	}
}