//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Presentation.Components.Synologen {
    
    public partial class AddFiles {
        protected System.Web.UI.WebControls.FileUpload uplFile1;
        protected System.Web.UI.WebControls.TextBox txtDesc1;
        protected System.Web.UI.WebControls.DropDownList drpCategory1;
        protected System.Web.UI.WebControls.FileUpload uplFile2;
        protected System.Web.UI.WebControls.TextBox txtDesc2;
        protected System.Web.UI.WebControls.DropDownList drpCategory2;
        protected System.Web.UI.WebControls.FileUpload uplFile3;
        protected System.Web.UI.WebControls.TextBox txtDesc3;
        protected System.Web.UI.WebControls.DropDownList drpCategory3;
        protected System.Web.UI.WebControls.FileUpload uplFile4;
        protected System.Web.UI.WebControls.TextBox txtDesc4;
        protected System.Web.UI.WebControls.DropDownList drpCategory4;
        protected System.Web.UI.WebControls.FileUpload uplFile5;
        protected System.Web.UI.WebControls.TextBox txtDesc5;
        protected System.Web.UI.WebControls.DropDownList drpCategory5;
        protected System.Web.UI.WebControls.Button btnAdd;
    }
}
