//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Presentation.Components.Synologen {
    
    public partial class Category {
        protected System.Web.UI.WebControls.Label lblHeader;
        protected System.Web.UI.WebControls.Label lblName;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvFirstName;
        protected System.Web.UI.WebControls.TextBox txtName;
        protected System.Web.UI.WebControls.DropDownList drpShopCategory;
        protected System.Web.UI.HtmlControls.HtmlGenericControl dGroups;
        protected System.Web.UI.WebControls.Label lblGroup;
        protected System.Web.UI.WebControls.DropDownList drpGroups;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.GridView gvCategory;
    }
}
