//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Presentation.Components.Synologen {
    
    public partial class ContractCompanies {
        protected System.Web.UI.WebControls.Literal ltHeading;
        protected System.Web.UI.WebControls.DropDownList drpContracts;
        protected System.Web.UI.WebControls.TextBox txtName;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvName;
        protected System.Web.UI.WebControls.TextBox txtCompanyCode;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvCompanyCode;
        protected System.Web.UI.WebControls.TextBox txtBankIDCode;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvBankIDCode;
        protected System.Web.UI.WebControls.RangeValidator vldBankIDCode;
        protected System.Web.UI.WebControls.TextBox txtAddress;
        protected System.Web.UI.WebControls.TextBox txtAddress2;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvAddress2;
        protected System.Web.UI.WebControls.TextBox txtZip;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvZip;
        protected System.Web.UI.WebControls.TextBox txtCity;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvCity;
        protected System.Web.UI.WebControls.CheckBox chkActive;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.GridView gvContractCompanies;
    }
}
