//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Presentation.Components.Synologen {
    
    public partial class ContractArticles {
        protected System.Web.UI.WebControls.Literal ltHeading;
        protected System.Web.UI.WebControls.DropDownList drpContracts;
        protected System.Web.UI.WebControls.RequiredFieldValidator reqContracts;
        protected System.Web.UI.WebControls.DropDownList drpArticles;
        protected System.Web.UI.WebControls.RequiredFieldValidator reqArticles;
        protected System.Web.UI.WebControls.TextBox txtPrice;
        protected System.Web.UI.WebControls.RangeValidator vldPrice;
        protected System.Web.UI.WebControls.CheckBox chkNoVAT;
        protected System.Web.UI.WebControls.TextBox txtSPCSAccountNumber;
        protected System.Web.UI.WebControls.RequiredFieldValidator reqSPCSAccountNumber;
        protected System.Web.UI.WebControls.CheckBox chkActive;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.GridView gvContractCustomerArticles;
    }
}
