//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Presentation.Components.Synologen {
    
    public partial class EditMember {
        protected System.Web.UI.WebControls.Literal ltHeader;
        protected System.Web.UI.WebControls.Label lblOrgName;
        protected System.Web.UI.WebControls.TextBox txtOrgName;
        protected System.Web.UI.WebControls.Label lblCategories;
        protected System.Web.UI.WebControls.DropDownList drpMemberCategories;
        protected System.Web.UI.WebControls.DropDownList drpShops;
		protected System.Web.UI.WebControls.DropDownList drpLocations;
        protected System.Web.UI.HtmlControls.HtmlGenericControl dAcountDetails;
        protected System.Web.UI.WebControls.Label lblUserName;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvUserName;
        protected System.Web.UI.WebControls.Label lblUsernameExists;
        protected System.Web.UI.WebControls.TextBox txtUserName;
        protected System.Web.UI.WebControls.Label lblPassword;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;
        protected System.Web.UI.WebControls.TextBox txtPassword;
        protected System.Web.UI.WebControls.Label lblVerifyPassword;
        protected System.Web.UI.WebControls.CompareValidator CompareValidator1;
        protected System.Web.UI.WebControls.TextBox txtVerifyPassword;
        protected System.Web.UI.WebControls.Label lblFirstName;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvFirstName;
        protected System.Web.UI.WebControls.TextBox txtFirstName;
        protected System.Web.UI.WebControls.Label lblLastName;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvLastName;
        protected System.Web.UI.WebControls.TextBox txtLastName;
        protected System.Web.UI.WebControls.Label lblEmail;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
        protected System.Web.UI.WebControls.RegularExpressionValidator revEmail;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.CheckBox chkActive;
        protected System.Web.UI.HtmlControls.HtmlGenericControl dPublicDetails;
        protected System.Web.UI.WebControls.Literal ltPublicHeader;
        protected System.Web.UI.WebControls.Label lblPublicEmail;
        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
        protected System.Web.UI.WebControls.TextBox txtPublicEmail;
        protected System.Web.UI.WebControls.Label lblContactFirstName;
        protected System.Web.UI.WebControls.TextBox txtContactFirstName;
        protected System.Web.UI.WebControls.Label lblContactLastName;
        protected System.Web.UI.WebControls.TextBox txtContactLastName;
        protected System.Web.UI.HtmlControls.HtmlGenericControl dActiveAccount;
        protected System.Web.UI.WebControls.CheckBox chkActivePublic;
        protected System.Web.UI.WebControls.Label lblAddress;
        protected System.Web.UI.WebControls.TextBox txtAddress;
        protected System.Web.UI.WebControls.Label lblAddress2;
        protected System.Web.UI.WebControls.TextBox txtAddress2;
        protected System.Web.UI.WebControls.Label lblZipCode;
        protected System.Web.UI.WebControls.TextBox txtZipCode;
        protected System.Web.UI.WebControls.Label lblCity;
        protected System.Web.UI.WebControls.TextBox txtCity;
        protected System.Web.UI.WebControls.Label lblMobile;
        protected System.Web.UI.WebControls.TextBox txtMobile;
        protected System.Web.UI.WebControls.Label lblPhone;
        protected System.Web.UI.WebControls.TextBox txtPhone;
        protected System.Web.UI.WebControls.Label lblFax;
        protected System.Web.UI.WebControls.TextBox txtFax;
        protected System.Web.UI.WebControls.Label lblTitle;
        protected System.Web.UI.WebControls.TextBox txtTitle;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected System.Web.UI.WebControls.TextBox txtDescription;
        protected System.Web.UI.WebControls.Label lblWeb;
        protected System.Web.UI.WebControls.TextBox txtWeb;
        protected System.Web.UI.HtmlControls.HtmlGenericControl dWysiwyg;
        protected System.Web.UI.WebControls.Label lblBody;
        protected Spinit.Wpc.Wysiwyg.WpcWysiwyg txtBody;
        protected System.Web.UI.WebControls.Label lblLocations;
        protected System.Web.UI.WebControls.CheckBoxList chklLocations;
        protected System.Web.UI.WebControls.Button btnSaveAndPublish;
        protected System.Web.UI.WebControls.Button btnSaveForLater;
        protected System.Web.UI.WebControls.Button btnSaveForApproval;
        protected System.Web.UI.WebControls.ValidationSummary vldsUser;
    }
}
