//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Presentation.Components.Synologen {
    
    public partial class EditOrder {
        protected System.Web.UI.WebControls.Literal ltOrderNumber;
        protected System.Web.UI.WebControls.Literal ltSPCSOrderNumber;
        protected System.Web.UI.WebControls.Literal ltSPCSValueIncludingVAT;
        protected System.Web.UI.WebControls.Literal ltSPCSValueExcludingVAT;
        protected System.Web.UI.WebControls.Literal ltContractName;
        protected System.Web.UI.WebControls.DropDownList drpCompanies;
        protected System.Web.UI.WebControls.TextBox txtRST;
        protected System.Web.UI.WebControls.RangeValidator vldRST;
        protected System.Web.UI.WebControls.DropDownList drpStatus;
        protected System.Web.UI.WebControls.TextBox txtUnit;
        protected System.Web.UI.WebControls.TextBox txtCustomerFirstName;
        protected System.Web.UI.WebControls.TextBox txtCustomerLastName;
        protected System.Web.UI.WebControls.TextBox txtPersonalIDNumber;
        protected System.Web.UI.WebControls.RequiredFieldValidator reqPersonalIDNumber;
        protected System.Web.UI.WebControls.RegularExpressionValidator regPersonalIDNumber;
        protected System.Web.UI.WebControls.CustomValidator vldCustomPersonalIDNumber;
        protected System.Web.UI.WebControls.TextBox txtPhone;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.Literal ltShopName;
        protected System.Web.UI.WebControls.Literal ltmemberName;
        protected System.Web.UI.WebControls.Literal ltSaleDate;
        protected System.Web.UI.WebControls.Literal ltUpdateDate;
        protected System.Web.UI.WebControls.Literal ltMarkedAsPayed;
        protected System.Web.UI.WebControls.DropDownList drpArticle;
        protected System.Web.UI.WebControls.RequiredFieldValidator reqArticle;
        protected System.Web.UI.WebControls.RequiredFieldValidator reqArticle2;
        protected System.Web.UI.WebControls.DropDownList drpNumberOfItems;
        protected System.Web.UI.WebControls.RequiredFieldValidator reqNumberOfItems;
        protected System.Web.UI.WebControls.TextBox txtNotes;
        protected System.Web.UI.WebControls.Button btnAddArticle;
        protected System.Web.UI.WebControls.GridView gvOrderItems;
        protected System.Web.UI.WebControls.CustomValidator vldCheckAnyOrderItems;
        protected System.Web.UI.WebControls.Repeater rptOrderHistory;
        protected System.Web.UI.WebControls.ValidationSummary vldSummary;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnAbort;
        protected System.Web.UI.WebControls.Button btnHalt;
        protected System.Web.UI.WebControls.Button btnAbortHalt;
    }
}
