//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Presentation.Components.Synologen {
    
    public partial class EditContract {
        protected System.Web.UI.WebControls.TextBox txtContractCustomerName;
        protected System.Web.UI.WebControls.TextBox txtContractCustomerCode;
        protected System.Web.UI.WebControls.TextBox txtContractCustomerDescription;
        protected System.Web.UI.WebControls.TextBox txtAddress;
        protected System.Web.UI.WebControls.TextBox txtAddress2;
        protected System.Web.UI.WebControls.TextBox txtZip;
        protected System.Web.UI.WebControls.TextBox txtCity;
        protected System.Web.UI.WebControls.TextBox txtPhone;
        protected System.Web.UI.WebControls.TextBox txtPhone2;
        protected System.Web.UI.WebControls.TextBox txtFax;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.CheckBox chkActive;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.ValidationSummary vldsUser;
    }
}
