//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Presentation.Components.Synologen {
	public partial class Files {
		protected System.Web.UI.WebControls.Label lblShow;
		protected System.Web.UI.WebControls.DropDownList drpFileCategories;
		protected System.Web.UI.WebControls.Button btnSetFilter;
		protected System.Web.UI.WebControls.Button btnShowAll;
		protected System.Web.UI.WebControls.GridView gvFiles;
	}
}