//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinit.Wpc.Synologen.Presentation {
    
    public partial class SynologenMain {
        protected System.Web.UI.WebControls.PlaceHolder phSynologenMenu;
        protected System.Web.UI.WebControls.PlaceHolder phSynologenSubMenu;
        protected System.Web.UI.WebControls.ValidationSummary validationSummary;
        protected System.Web.UI.WebControls.ValidationSummary validationSummarySuccess;
        protected System.Web.UI.WebControls.ContentPlaceHolder phSynologen;
    }
}
